language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
  - DEPENDENCIES=""
  - DEPENDENCIES="--prefer-lowest"

php:
  - 7.1
  - 7.2

install:
  - composer update --no-interaction --prefer-dist $DEPENDENCIES

script:
  - vendor/bin/parallel-lint src tests
  - vendor/bin/phpcs --extensions=php --encoding=utf-8 -sp src tests
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - vendor/bin/phpstan analyse -c phpstan.neon -l 5 src tests

after_success:
  - >
    if [ $TRAVIS_PHP_VERSION == "7.2" ]; then
    wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
    && php ./coveralls.phar --verbose
    || true; fi
